### ISSUE TITLE
JourneyMap Compatibility

### ISSUE THREAD

**Issue by BlayTheNinth** [blay09/DefaultKeyConfig#19]

**Comment by SnowShock35** [comment]
@blay09 @techbrew-mc So it appears this issue has now escalated further as none of the key bindings will save as of the latest version of JourneyMap. I imagine this is due to techbrew updating the key bindings however, it now causes all of the keybindings not to get saved when using Default Options. It's a shame really as now all the keybindings are messed up in mod packs. 

### Key Info

- Minecraft 1.12.1
- Minecraft Forge 14.22.0.2474
- Default Options 1.12.1-9.2.4
- JourneyMap 1.12.1-5.5.0b4

**Comment by techbrew-mc** [comment]
Heya @blay09 - 

JM uses extended classes of Keybinding so I can detect changes.  Any chance there's an issue with using ReflectionHelper here?https://github.com/blay09/DefaultOptions/blob/1.12/src/main/java/net/blay09/mods/defaultoptions/DefaultOptions.java#L308

That said, I wouldn't normally think there'd be an issue using ReflectionHelper on the parent class.  Still trying to recreate the problem in a dev environment.

**Comment by BlayTheNinth** [comment]
It's actually just a matter of loading order / registration time, JourneyMap registers its KeyBindings quite late (in postInit), and that's where Default Options applies the key defaults. If Default Options loads first, they're not gonna be caught.

**Comment by SnowShock35** [comment]
So that's the problem then. Need to load key-bindings earlier. \o/

**Comment by BlayTheNinth** [comment]
Fixed it over here for now by just forcing to load before JourneyMap. Still I'd probably move the keybinds to init, since I don't think there's any good reason to delay their registration.

**Comment by techbrew-mc** [comment]
JM 5.6.0b1 and later will have keybindings registered during init instead of postInit.
