### ISSUE TITLE
[Bug] Not loading the default set resource pack before title screen

### ISSUE THREAD

**Issue by SnowShock35** [blay09/DefaultKeyConfig#2]
Minecraft 1.7.10
Forge 10.13.4.1448
Default KeyConfig & Options 1.0.6

Description of Issue:
So the gist of the issue is that the mod needs to load before it gets to the main menu and before all textures ect are loaded. Because
1. It's not applying the textures from resource packs
2. And sound options don't get applied

Even if the game is reloaded the resource pack is still not added. Assuming it's copying the file each time so that if it had changed it sees those changes, maybe?

**Comment by blay09** [comment]
Right, I'll make it apply the default options at the very beginning.

Not sure I understand the last sentence, but the default options file is only copied over once if no other exists, so that user-made settings don't get overridden every time (keys work a little differently as the mod accounts for new mod keybindings being added there).

**Comment by blay09** [comment]
Fixed version is now up on CurseForge :)

http://minecraft.curseforge.com/mc-mods/232131-default-keyconfig-options/files
